FROM node:18

ARG service_name

USER node
WORKDIR /home/node

COPY ./$service_name /home/node
COPY ./shared /home/node/src/shared

RUN npm install 
RUN npm run build

COPY --from=builder /home/node/node_modules/ /home/node/node_modules
COPY --from=builder /home/node/.env /home/node/
COPY --from=builder /home/node/package*.json /home/node/
COPY --from=builder /home/node/src/prisma/schema.prisma /home/node/
COPY --from=builder /home/node/dist/ /home/node/dist/

EXPOSE 3000

CMD ["node", "dist/main.js"]